export const CART_ACTION_TYPES = {
  TOGGLE_CART_STATUS: 'cart/TOGGLE_CART_STATUS',
  SET_CART_ITEMS: 'cart/SET_CART_ITEMS', 
  SET_CART_COUNT: 'cart/SET_CART_COUNT',
  SET_CART_TOTAL: 'cart/SET_CART_TOTAL'
}